backend/backend/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('mainpage.urls')),
    path("project/",include('projects.urls')),
    path("blog/",include('blogs.urls')),
    path("event/",include('event.urls')),
    path("course/",include('course.urls')),
    path("quiz/",include('quizapp.urls')),
    path("job/",include('recurit.urls')),
    path("chat/",include('chat.urls')),


    path('register/',user_views.register, name='register'),
    path('company/register/',user_views.rec_register, name='company-register'),
    path('company/update/',user_views.company_profile_update, name='company-update'),
    path('teacher/profile/update/',user_views.update_teacher_profile, name='teacher-update'),
    path('teacher/register/',user_views.update_to_teacher, name='teacher-register'),
    path('profile/',user_views.profile, name='profile'),
    path('company/<str:username>',user_views.view_job_profile, name='company-profile'),
    path('teacher/<str:username>',user_views.view_teacher, name='teacher-profile'),
    path('profile/<int:pk>',user_views.shareProfile.as_view(), name='share-profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

backend/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.get_room,name='chat'),
    path('public/',views.get_public_room,name='public-chat'),
    path('student/<int:pk>',views.chat_with_Student,name='teacher-chat'),
    path('<str:room_name>/', views.room, name='room'),
]

backend/projects/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('',projectListView.as_view(),name='project-list'),
    path('create/',projectCreateView.as_view(),name='project-create'),
    path('likes/',like_main_post, name='like_main_post'),
    path('comment/',comment, name='comment'),
    path('<int:pk>/update/',projectUpdateView.as_view(), name='project-update'),
    path('<int:pk>/delete/',projectDeleteView.as_view(), name='project-delete'),
    path('illegal/user/',illegal_tresspass,name='illegal-trespass'),
]

backend/projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.urls import reverse
import os 

def video_validator(value):
    limit = 2 * 1024 * 1024
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.mp4','.mov','.wmv','.avi','.mkv']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension.')
    # if value.size > limit:
    #     raise ValidationError('File too large. Size should not exceed 2 MiB.')
    #  validators=[video_validator],
    pass

class projects(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    video = models.FileField(upload_to='project/video/', validators=[video_validator])
    like = models.ManyToManyField(User, related_name='blog_posts', blank=True, default=None)

    def __str__(self):
        return f'{self.user} - project'

    def get_absolute_url(self):
        return reverse('project-list')

    
    def num_likes(self):
        return self.like.count()

class Comment(models.Model):
    project = models.ForeignKey(projects, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    body = models.CharField(max_length=255)
    date_added = models.DateTimeField(auto_now_add=True)
   
    def __str__(self):
        return f'{self.project.user} - comment'

backend/projects/forms.py
from django.forms import ModelForm
from .models import *

class commentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(commentForm, self).__init__(*args, **kwargs)
        self.fields['body'].widget.attrs['placeholder'] = "Post a comment"
    
    class Meta:
        model = Comment
        fields = ['body']

backend/projects/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from .forms import *
from django.views.generic import ListView,CreateView,DeleteView,DetailView,UpdateView
from django.http import HttpResponseRedirect, request,HttpResponse,JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin , UserPassesTestMixin
from event.models import *
from django.db.models import Count
try:
    from django.utils import simplejson as json
except ImportError:
    import json
# Create your views here.
class projectListView(LoginRequiredMixin,ListView):
    model = projects   
    template_name='projects-list.html'
    context_object_name='projects'
    ordering=['-date_posted']
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events = event.objects.all().annotate(num_tags=Count('userEnrolled')).order_by('-num_tags')[:4]
        context['comment_form'] = commentForm()
        context['events'] = events
        return context

class projectCreateView(LoginRequiredMixin,CreateView):
    model =  projects
    fields = ['video','description']
    template_name = 'project_createView.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@login_required
def like_main_post(request):
    post = get_object_or_404(projects, id=request.POST.get('id',None))
    is_like = False
    if post.like.filter(id=request.user.id).exists():
        post.like.remove(request.user)
        is_like = False
    else:
        is_like = True
        post.like.add(request.user)

    context = {
        'likes_count':post.like.count(),
        'is_like':is_like,
    }
    return HttpResponse(json.dumps(context), content_type='application/json')


@login_required
def comment(request):
    print("jojo")
    prj = get_object_or_404(projects, id=request.POST.get('post_id',None))
    print(request.POST.get('id',None))
    if request.method == 'POST':
        comment = Comment(project=prj,user=request.user,body=request.POST.get('datas'))
        comment.save()

    context={
            'username': request.user.username,
            'userid':request.user.id,
            'body': request.POST.get('datas'),
            'image':request.user.profile.image.url,
            'date':str(comment.date_added),
            'number_of_comments': Comment.objects.filter(project=prj).all().count(),
        }

    return HttpResponse(json.dumps(context), content_type='application/json')




class projectDetailView(LoginRequiredMixin,DetailView):
    model = projects
    template_name = 'project_detail.html'
    def get_context_data(self, **kwargs):
        liked = True
        prj = get_object_or_404(projects,id=self.kwargs['pk'])
        total_like = prj.num_likes()

        if prj.like.filter(id=self.request.user.id).exists():
            liked = False
        
        context = super().get_context_data(**kwargs)
        context['total_like'] = total_like
        context['liked'] = liked
        return context

class projectUpdateView(LoginRequiredMixin,UpdateView):
    model = projects
    template_name  = 'project_edit.html'
    fields = ['video','description']

    # def get(self, request, *args, **kwargs):
    #     prj = self.get_object()
    #     if self.request.user == prj.user:
    #         return HttpResponseRedirect(reverse('illegal-trespass'))
    
    def get(self, request, *args, **kwargs):
        prj = self.get_object()
        if self.request.user != prj.user:
            return HttpResponseRedirect(reverse('illegal-trespass'))
        else:
            return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    def test_func(self):
        prj = self.get_object()
        if self.request.user == prj.user:
            return True
        return False
    

class projectDeleteView(LoginRequiredMixin,DeleteView):
    model = projects
    template_name  = 'projects_confirm_delete.html'
    success_url = '/project/'

    def get(self, request, *args, **kwargs):
        prj = self.get_object()
        if self.request.user != prj.user:
            return HttpResponseRedirect(reverse('illegal-trespass'))
        else:
            return super().get(request, *args, **kwargs)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False

def illegal_tresspass(request):
    return render(request,'illegal.html')

backend/projects/templates/illegal.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-12 col-md-10 container-style">
        <div class="blog-sec">
            <h1>DONT TRY TO BE SMART IDIOT INSTEAD CREATE YOUR OWN POST YOU PIECE OF SHIT</h1>
        </div>
    </div>
</div>
{% endblock content %}

backend/projects/templates/project_createView.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-12 col-md-12 container-style">
      <div class="blog-sec">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4"> Project </legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Post</button>
    </div>
</form>
</div>
</div>
</div>
{% endblock content %}

backend/projects/templates/project_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4"> Project </legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Post</button>
    </div>
</form>
{% endblock content %}

backend/projects/templates/project_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-12 col-md-10 container-style">
        <div class="blog-sec">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Project </legend>
                <!-- {{ form|crispy }} -->
                <div class="row">
                    <video class="blog-video" controls><source src="{{form.instance.video.url}}"></video>
                </div>
                <div class="row">
                    {{form.video|as_crispy_field}}
                </div>
                <div class="row">
                    <div class="col-12 about-project">
                        {{form.description |as_crispy_field}}
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
    </div>
</div>
{% endblock content %}

backend/projects/templates/projects-list.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-12 col-md-10 container-style">
      <a class="add_prj" href="{% url 'project-create' %}">
      <div class="blog-sec">
        <div class="row">
          <div class="col-md-2 col-12"></div>
          <div class="col-md-9 col-12">
            <h1>
              Show World your project <i class="fas fa-plus"></i>
            </h1>
          </div>
        </div>
      </div>
    </a>
        {% for project in projects%}
        <div class="blog-sec">
            <!-- blog post user area -->
            <div class="row">
              <div class="col-1">
                <img class="rounded-circle article-img" src="{{ project.user.profile.image.url}}">
              </div>
              <div class="col-9 username">
                <h5>{{ project.user }}</h5>
              </div>
              <div class="col-2">
                {% if project.user == user %}
                <div class="dropdown">
                    <button class="btn " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-ellipsis-v"></i>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <a class="dropdown-item" href="{% url 'project-update' project.id %}">Edit</a>
                        <a class="dropdown-item" href="{% url 'project-delete' project.id %}">Delete</a>
                    </ul>
                  </div>
                <!-- <div class="dropdown edit">
                    <button class="btn btn-secondary " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-h"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="">Edit</a>
                        <a class="dropdown-item" href="">Delete</a>
                    </div>
                </div> -->
                {% endif %}
              </div>
            </div>
            <hr>
            <!-- blog-post -->
            <div class="row">
             <video class="blog-video" controls><source src="{{ project.video.url }}"></video>
            </div>
            <div class="row">
                <div class="col-12 about-project">
                    <p>
                        {{ project.description }}
                    </p>
                </div>
            </div>
            <!-- like comment -->
            <div class="row">
              <ul class="like-com">
                <li>
                  {% if user not in project.like.all %}
                      <button type="submit" id="like" name="post_id" value="{{ project.id }}">
                          <i class="fas fa-heart"></i> Like
                      </button>   
                      <span class="number_of_like">{{ project.like.all.count }} </span>
                  {% else %}
                      <button type="submit" id="like" style="color: #e44d3a;"  name="post_id" value="{{ project.id }}"><i class="fas fa-heart "></i> Like</button><span class="number_of_like">{{ project.like.all.count }}  </span>
                  {% endif %}
                  <!-- <button><i class="fas fa-heart"></i> Like</button> -->
                </li>
                <li>
                  <button class="com" id="{{ forloop.counter }}" onclick="showComment(this.id)" ><i class="fas fa-comment-alt"></i> Comment {{project.comments.all.count}}</button>
                </li>
              </ul>
            </div>
            <div class="row">
                <small class="text-muted">{{ project.date_posted|date:"F d, Y" }}</small>
            </div>
          </div>

          <!-- comment section -->
          <div class="comment-sec" id="comment{{forloop.counter}}" style="display: none;" >
            <div class="row">
              <!-- comments -->
              <div class="comment-list">
                <div class="row" id='commentList{{project.id}}'>
                  {% for comment in project.comments.all %}
                  <!-- comment -->
                  <div class="comment row">
                    <div class="col-1">
                      <img src="{{ comment.user.profile.image.url}}" class="rounded-circle comment-img">
                    </div>
                    <div class="col-11">
                      <div class="row">
                        <small class="text-muted">{{ comment.date_added|date:"F d, Y" }}</small>
                      </div>
                      <div class="row">
                        <h5><a class="username_tag" href="{%url 'share-profile' comment.user.id %}">{{ comment.user }}</a></h5>
                      </div>
                      <div class="row">
                        <p>
                          {{comment.body}}
                        </p>
                      </div>
                    </div>
                  
                  </div>
                  <hr>
                  {% endfor %}
                </div>
              </div>
            </div>
            <!-- comment box -->
            <form id="comment_sec" action="{% url 'comment' %}" method="POST" data-attr="{{ project.id }}">
                <div class="row">
                <div class="col-10">
                  <!-- {% csrf_token %}
                  {{ comment_form.body }} -->
                  <input id="id_body" type="text" placeholder="Comment">
                </div>
                <div class="col-2">
                  <button class="comment-button" type="submit" name="comment_id" value="{{ project.id }}">Add</button>
                  
                </div>
              </div>
              </form>
          </div>
        {% endfor %}




    </div>
    <div class="col-md-2">
      <div class="sidebar">
        <div class="ex1">
          <h3>Top events</h3>
        </div>
      </div>
      <br>
      {% for event in events %}
      {% if user not in event.userEnrolled.all %}
        <div class="sidebar">
          <div class="ex1">
            <h3>{{event.title}}</h3>
            <p>
              Cost : {{event.cost}} <br>
              Last Day Of Registration : {{event.last_day_of_registration}} <br>
            </p>
            <br>
            <div class="event-button-sec">
              <a class="event-button" href="{% url 'event-enroll' event.id%}">Enroll</a>
            </div>
          </div>
        </div>
        <br>
      {% endif %}
      {% endfor%}
    </div>
</div>

{% endblock content %}
{% block javascript %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous"></script>
  <script>
    $('#like').click(function(){
            $.ajax({
                    type: "POST",
                    url: "{% url 'like_main_post' %}",
                    data: {'id': $(this).attr('value'),'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: "json",
                    success: function(response) {
                        console.log("yeahhh")
                        if(response.is_like){
                            $('#like').addClass("active");
                            $('.number_of_like').text(response.likes_count);
                            }else{
                            $('#like').removeClass("active");
                            $('.number_of_like').text(response.likes_count);
                        }
                            console.log('Company likes count is now ' + response.likes_count);
                        },
                        error: function(rs, e) {
                            console.log(rs.responseText);
                        }
                }); 
            })

            $('#comment_sec').submit(function(e){
            e.preventDefault();
            console.log($(e.target).data('attr'))
            $.ajax({
                type:"POST",
                url: "{% url 'comment' %}",
                data: {
                    'post_id':$(e.target).data('attr'),
                    'datas':$('#id_body').val(),
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: "json",
                success: function(response) {
                    addComment(response.username,response.userid,response.image,response.body,response.date,$(e.target).data('attr'))
                    $('#id_body').val('')
                    $('.comment_text'+$(e.target).data('attr')).text('Comment '+response.number_of_comments)
                    },
                error: function(rs, e) {
                    console.log(rs.responseText);
                }
            });
        })

        function addComment(username,userid,image,body,postDate,id){
            main = document.getElementById('commentList'+id)


            var mainDiv = document.createElement('div');
            mainDiv.classList.add('comment');
            mainDiv.classList.add('row');
            
            var imgDiv = document.createElement('div');
            imgDiv.classList.add('col-1')
            var img = document.createElement('img');
            img.setAttribute('src',image);
            img.classList.add('rounded-circle');
            img.classList.add('comment-img');
            imgDiv.appendChild(img);
            
            var cmdDiv = document.createElement('div');
            cmdDiv.classList.add('col-11');
            
            var dateDiv = document.createElement('div')
            dateDiv.classList.add('row');
            var stag = document.createElement('small')
            stag.classList.add('text-muted')
            var spanTag = document.createElement('span')
            let dt = moment(postDate, "YYYY-MM-DD");
            stag.innerHTML = dt.format('LL')
            dateDiv.appendChild(stag)

            var userdiv = document.createElement('div')
            userdiv.classList.add('row')
            var h5tag = document.createElement('h5')
            var atag = document.createElement('a');
            atag.href = '/profile/'+userid
            atag.innerHTML = username
            atag.classList.add('username_tag')
            h5tag.appendChild(atag);
            userdiv.append(h5tag)

            var bdiv = document.createElement('div')
            bdiv.classList.add('row')
            var pTag = document.createElement('p');
            pTag.innerHTML = body
            bdiv.appendChild(pTag)


            cmdDiv.appendChild(dateDiv)
            cmdDiv.appendChild(userdiv)
            cmdDiv.appendChild(bdiv)
            mainDiv.appendChild(imgDiv)
            mainDiv.appendChild(cmdDiv)
            main.appendChild(mainDiv)
        }
  </script>

{% endblock javascript %}

backend/projects/templates/projects_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-12 col-md-10 container-style">
        <div class="blog-sec">
            <div class="content-section">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4"> Delete Post </legend>
                        <h2> Are you sure to delete the post </h2>

                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-danger" type="submit">Delete</button>
                        <a class="btn btn-outline-secondary" href="{% url 'project-list' %}">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}